[package]
name = "rust-by-example-coding-v2"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "xtask"
]


[dependencies]

[[example]]
name = "01-comments"
path = "examples/01_hello_word/comments.rs"

[[example]]
name = "01-formatted_print-debug"
path = "examples/01_hello_word/formatted_print/debug.rs"

[[example]]
name = "01-formatted_print-display"
path = "examples/01_hello_word/formatted_print/display.rs"

[[example]]
name = "01-formatted_print-formatting"
path = "examples/01_hello_word/formatted_print/formatting.rs"

[[example]]
name = "02-primitives-literals_and_operators"
path = "examples/02_primitives/literals_and_operators.rs"

[[example]]
name = "02-primitives-tuples"
path = "examples/02_primitives/tuples.rs"


[[example]]
name = "02-primitives-arrays_and_slices"
path = "examples/02_primitives/arrays_and_slices.rs"

[[example]]
name = "03-custom_types-structures"
path = "examples/03_custom_types/structures.rs"

[[example]]
name = "03-custom_types-enums"
path = "examples/03_custom_types/enums.rs"

[[example]]
name = "03-custom_types-enums_use"
path = "examples/03_custom_types/enums_use.rs"

[[example]]
name = "03-custom_types-structuenums_c_likeres"
path = "examples/03_custom_types/enums_c_like.rs"

[[example]]
name = "03-custom_types-enums_linked_list"
path = "examples/03_custom_types/enums_linked_list.rs"

[[example]]
name = "03-custom_types-constants"
path = "examples/03_custom_types/constants.rs"

[[example]]
name = "04-variable_bindings-summary"
path = "examples/04_variable_bindings/summary.rs"

[[example]]
name = "04-variable_bindings-mutablility"
path = "examples/04_variable_bindings/mutablility.rs"

[[example]]
name = "04-variable_bindings-scope_and_shadowing"
path = "examples/04_variable_bindings/scope_and_shadowing.rs"


[[example]]
name = "04-variable_bindings-declare_first"
path = "examples/04_variable_bindings/declare_first.rs"


[[example]]
name = "04-variable_bindings-freezing"
path = "examples/04_variable_bindings/freezing.rs"