[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
project-root = "0.2.2"
walkdir = "2"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0.98"
toml_edit = "0.22.27"

